project_prueba_tpo/app_solicitud/urls.py
# from django.contrib import admin
# from django.urls import path , include
from django.urls import path
from .router import router


from .views import      SolicitudListView   \
                    ,   SolicitudDetailView \
                    ,   SolicitudCreateView \
                    ,   SolicitudUpdateView \
                    ,   SolicitudDeleteView

app_name = "solicitud"

urlpatterns = [
    path("", SolicitudListView.as_view(), name="all"),
    path("create/", SolicitudCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", SolicitudDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", SolicitudUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", SolicitudDeleteView.as_view(), name="delete")

]

urlpatterns += router.urls

project_prueba_tpo/project_prueba_tpo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexPage, NosotrosPage, ServiciosPage, AutogestionPage


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', IndexPage.as_view(), name="index_page"),
    path('nosotros/', NosotrosPage.as_view(), name="nosotros_page"),
    path('servicios/', ServiciosPage.as_view(), name="servicios_page"),
    path('autogestion/', AutogestionPage.as_view(), name="autogestion_page"),
    path('solicitud/', include('app_solicitud.urls')),
]

project_prueba_tpo/app_solicitud/models.py
from django.db import models

# Create your models here.
class Solicitud(models.Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model
    """
    
    mensaje = models.CharField(max_length=200)
    prioridad = models.PositiveSmallIntegerField(blank=False, null=False)
    pto = models.FloatField(blank=True, null=True)
    creado = models.DateTimeField(auto_now_add = True, auto_now = False, blank = True)
    actualizado = models.DateTimeField(auto_now = True, blank = True)
    
    
    
    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase
    
    class Meta:
      db_table = "solicitud_table"
    
    def __str__(self):
        return f"La solicitud: {self.mensaje}, Prioridad {self.prioridad}, Hora {self.creado}, Actualizada {self.actualizado}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

project_prueba_tpo/app_solicitud/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView

from .models import Solicitud

# Create your views here.


class SolicitudBaseView(View):
    template_name = 'solicitud.html'
    model = Solicitud 
    fields = '__all__'
    success_url = reverse_lazy('solicitud:all')
    
class SolicitudListView(SolicitudBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LAS SOLICTUDES
    """
    
class SolicitudDetailView(SolicitudBaseView,DetailView):
    template_name = "solicitud_detail.html"
    
class SolicitudCreateView(SolicitudBaseView,CreateView):
    template_name = "solicitud_create.html"
    extra_context = {
        "tipo": "Crear solicitud"
    }


class SolicitudUpdateView(SolicitudBaseView,UpdateView):
    template_name = "solicitud_update.html"
    extra_context = {
        "tipo": "Actualizar solicitud"
    }

class SolicitudDeleteView(SolicitudBaseView,DeleteView):
    template_name = "solicitud_delete.html"
    extra_context = {
        "tipo": "Borrar solicitud"
    }

project_prueba_tpo/project_prueba_tpo/views.py
from django.views.generic import TemplateView

class IndexPage(TemplateView):
    template_name = "bloques/index.html"
    extra_context = {
        "titulo_pagina" : "Bienvenidos a mi empresa"
        }
    
class NosotrosPage(TemplateView):
    template_name = "bloques/nosotros.html"
    extra_context = {
        "titulo_pagina" : "NOSOTROS"
        }
    
class ServiciosPage(TemplateView):
    template_name = "bloques/servicios.html"
    extra_context = {
        "titulo_pagina" : "SERVICIOS"
        }
        
class AutogestionPage(TemplateView):
    template_name = "bloques/autogestion.html"
    extra_context = {
        "titulo_pagina" : "Autogestion"
        }

project_prueba_tpo/app_solicitud/templates/solicitud.html
{% extends 'base_template.html' %}

{% block content %}


<main>
    <div class="main-color-solicitud">
        <h1>Todas las solicitudes</h1>
        <h2><a href="{% url 'solicitud:create' %}">CREAR SOLICITUD</a></h2>
        {% for solicitud in solicitud_list%}
        <div class="list">
            <span>
                <p>{{forloop.counter}}</p>
            </span>
            <span>
                <p>{{solicitud.mensaje}}</p>
            </span>
            
            <span>
                <label for="">Detalle: </label>
                <br>
                <a href="{% url 'solicitud:detail' solicitud.id %}">+</a>
            </span>
            <span>
                <label for="">Editar: </label>
                <br>
                <a href="{% url 'solicitud:update' solicitud.id %}">+</a>
            </span>
            <span>
                <label for="">Borrar: </label>
                <br>
                <a href="{% url 'solicitud:delete' solicitud.id %}">+</a>
            </span>
        </div>
        {% endfor %}
    </div>
    <br>
</main>
<br>

{% endblock %}

project_prueba_tpo/app_solicitud/templates/solicitud_create.html
{% extends 'base_template.html' %}
{% block content %}

<main>
    <div class="main-color-solicitud">
        <h1>CREAR SOLICITUD</h1>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'solicitud:all' %}">Volvamos al Inicio</a>
    </div>
</main>
{% endblock %}

project_prueba_tpo/app_solicitud/templates/solicitud_delete.html
{% extends 'base_template.html' %} 
{% block content %}


<main>
    <div class="main-color-solicitud">
        <h1>Estas seguro que deseas borrar esta solicitud?</h1>
        <h2>{{solicitud.mensaje}}</h2>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'solicitud:all' %}">Cancelar</a>
    </div>
</main>
{% endblock %}

project_prueba_tpo/app_solicitud/templates/solicitud_detail.html
{% extends 'base_template.html' %}
{% block content %}

<main>
    <div class="main-color-solicitud">
        <h1>Solicitud</h1>
        <h2>{{solicitud.mensaje}}</h2>
        
        {% for label, value in solicitud.get_fields %}
        
            <p><u><strong>{{label | upper}}</strong></u></p>

            <p><em>{{value}}</em></p>
        
        {% endfor %}
        
        <a href="{% url 'solicitud:all' %}">ATRAS</a>
    </div>
</main>
{% endblock %}

project_prueba_tpo/app_solicitud/templates/solicitud_update.html
{% extends 'base_template.html' %}
{% block content %}

<main>
    <div class="main-color-solicitud">
        <h1>Actualizar Solicitud</h1>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'solicitud:all' %}">Volvamos al Inicio</a>
    </div>
</main>
{% endblock %}

project_prueba_tpo/templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static './css/base-style.css' %}">
        <link rel="stylesheet" href="{% static './css/main.css' %}">
        <title>Servicios de Internet</title>
    </head>
    
    <body class="content">
        <center>
           
            <!-- Menú de navegación -->
            <nav>
                <ul>
                    <li><a class="active" href="{% url 'index_page' %}"><img src="{% static './assets/img/comienzo.png' %}" title="Inicio"height="50px" width="50px"></a></li>
                    <li><a href="{% url 'nosotros_page' %}"><img src="{% static './assets/img/manual.png' %}" title="Institucional"height="50px" width="50px"></a></li>
                    <li><a href="{% url 'servicios_page' %}"><img src="{% static './assets/img/apoyo-tecnico.png' %}" title="Servicios"height="50px" width="50px"></a></li>
                    <li><a href="{% url 'autogestion_page' %}"><img src="{% static './assets/img/charlar.png' %}" title="Autogestión"height="50px" width="50px"></a></li>
                    <li>
                        <a href="{% url 'solicitud:all' %}"><img src="{% static './assets/img/solicitud.png' %}" title="Solicitud"height="50px" width="50px"></a></li>
                    </li>
                </ul>
            </nav>

            <!-- Logo -->
            <header class="logo-container">
                <img src="{% static './assets/img/logo5.png' %}" alt="logo_izquierda">

                    <h1>{{titulo_pagina}}</h1>

                <img src="{% static './assets/img/logo5.png' %}" alt="logo_derecha">
            

            </header>

            
            {% block content %}
            {% endblock %}

            <footer>
                <strong>© 2023 Mi empresa - Todos los derechos reservados</strong>
            </footer>
        </center>
    </body>
</html>

project_prueba_tpo/templates/bloques/autogestion.html
{% extends "base_template.html" %}


{% load static %}

{% block content %}
<!--Cabecera-->
<head>
    <link rel="stylesheet" href="{% static './css/autogestion.css' %}">
</head>

<!-- Contenido principal -->

<p>Tenes dudas, consultas sobre nuestros paquetes o como funciona nuestra politica de soporte, completa el siguiente formulario y te contactaremos a la brevedad.</p>

<section>

    <img src="{% static './assets/img/checklist.png' %}">
            
    <form id="formulario">
       
        <ul class="formulario">
            <div>
                <li>
                    <label for="name">Nombre:
                        <input type="text"  name="name" size="55" placeholder="Escribe aquí...">
                    </label>
                </li>
            </div>
            <!-- <br> -->
            <div>
                <li>
                    <label for="mail">Correo electronico:</label>
                        <input type="email" name="mail" size="55" placeholder="Escribe aquí...">
                    </label> 
                </li>
            </div>
            <!-- <br> -->
            <div>
                <li>
                    <label for="msg">Mensaje:
                        <textarea type="text" name="msg" rows="5" cols="55" placeholder="Escribe aquí..."></textarea>
                    </label>
                </li>
            </div>
            <!-- <br> -->
            <div>
                <li class="button">
                    <button type="submit">
                        Enviar
                    </button>
                </li>
            </div>
        </ul>
        
    </form>
    
</section>

<!-- Script -->
<script src="{% static './assets/scripts/script.js' %}"></script>

{% endblock %}

project_prueba_tpo/templates/bloques/index.html
{% extends "base_template.html" %}
{% load static %}





<!DOCTYPE html>
<html lang="en">
    <!-- <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=, initial-scale=1.0">
        <title>💻 Servicios de Internet 🖥️</title>
        <link rel="stylesheet" href="{ % static './css/styles.css' % }">
    </head> -->
    
    

    {% block content %}
    <!--Cabecera-->
    <head>
        <link rel="stylesheet" href="{% static './css/style-index.css' %}">
    </head>
                
    
    <!--Contenido principal-->
    <body class="content">

             
                    
            <!-- Párrafo de definición de la empresa -->
            <!-- Contenido principal -->

            <div class="contenedor content">
              <section>
                <p>
                  ¡Bienvenido a nuestra página de inicio!<br><br>
                  En nuestra empresa, nos dedicamos apasionadamente a brindar servicios integrales de última generación en el campo de las telecomunicaciones. Nuestro enfoque se centra en proporcionar soluciones de conectividad confiables y de alta velocidad, que incluyen servicios de internet, telefonía, FTTH (Fiber to the Home) e IPTV (Internet Protocol Television).<br><br>
                  Como líderes en el mercado, nos enorgullece ofrecer a nuestros clientes una experiencia incomparable en términos de velocidad, calidad y variedad de servicios. Nuestro equipo altamente capacitado y tecnológicamente avanzado está comprometido en garantizar que todos los aspectos de su conexión a Internet, telefonía y entretenimiento sean excepcionales.<br><br>
                  Nos destacamos por nuestra infraestructura de vanguardia, que nos permite brindar conexiones de fibra óptica de alta velocidad y estabilidad, garantizando una experiencia de navegación fluida y sin interrupciones. Además, nuestro servicio de IPTV le ofrece acceso a una amplia gama de contenido televisivo, incluyendo canales nacionales e internacionales, películas, series y eventos deportivos, todo ello transmitido a través de nuestra red segura y confiable.<br><br>
                  Nuestra misión es ser el socio preferido de nuestros clientes, brindándoles servicios de telecomunicaciones de primera clase que satisfagan sus necesidades y superen sus expectativas. Nos esforzamos por establecer relaciones duraderas con nuestros clientes, basadas en la confianza, la transparencia y el excelente servicio al cliente.<br><br>
                  Nuestra visión es ser líderes en la industria de las telecomunicaciones, impulsando la innovación y ofreciendo soluciones tecnológicas avanzadas que transformen la forma en que las personas se conectan, se comunican y disfrutan del entretenimiento en la era digital.<br><br>
                  Le invitamos a explorar nuestra página y descubrir cómo nuestros servicios pueden mejorar su vida digital. Estamos aquí para brindarle una experiencia de telecomunicaciones excepcional y convertirnos en su socio confiable en el mundo conectado de hoy.<br><br>
                  ¡Gracias por visitarnos y esperamos poder servirle pronto!
                </p>
              </section>
            </div>
        
            <!-- Contenido principal -->
            <div class="contenedor">
                <div class="cont-images">
                
                    <div class="card" div onclick="window.location.href='servicios#internet'" style="background-image: url(./static/assets/img/img-ind-001.jpg);">
                        <div class="textos" id="internet">
                            <h3>Internet</h3>
                            <p>Fibra Optica</p>
                        </div>
                    </div>
                
                    <div class="card" div onclick="window.location.href='servicios#telefonia'" style="background-image: url(./static/assets/img/img-ind-002.jpg);">
                        <div class="textos" id="telefonia">
                            <h3>Telefonía</h3>
                            <p>Telefonía VOIP</p>
                        </div>
                    </div>
                    <div class="card" div onclick="window.location.href='servicios#television'" style="background-image: url(./static/assets/img/img-ind-003.jpg);">
                        <div class="textos" id="television">
                            <h3>Televisión</h3>
                            <p>Televisión por IP</p>
                        </div>
                    </div>
                    <div class="card" div onclick="window.location.href='servicios#live_stream'" style="background-image: url(./static/assets/img/img-ind-004.jpg);">
                        <div class="textos" id="live_stream">
                            <h3>Live Stream</h3>
                            <p>Servicio de streaming</p>
                        </div>
                    </div>
                    <div class="card" div onclick="window.location.href='servicios#cine'" style="background-image: url(./static/assets/img/img-ind-005.jpg);">
                        <div class="textos" id="cine">
                            <h3>Servcios CINE</h3>
                            <p>Disfruta el mejor cine</p>
                        </div>
                    </div>
                    <div class="card" div onclick="window.location.href='servicios#web'" style="background-image: url(./static/assets/img/img-ind-006.jpg);">
                        <div class="textos" id="web">
                            <h3>Servicios Web</h3>
                            <p>Front-End y Back-End</p>
                        </div>
                    </div>
                </div>
            
            </div>
            <br>
            <h2 style="text-align: center;">Ubicacion</h2>
            <section class="datmap">
            
            
            <div class="mapa">

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28486.66395154346!2d-65.31595754917659!3d-26.81344580776341!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9422433a2ee1bffb%3A0xc5d4083eee0d98b1!2sYerba%20Buena%2C%20Tucum%C3%A1n!5e0!3m2!1ses-419!2sar!4v1685407821543!5m2!1ses-419!2sar" width="400" height="300" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div id="datos">

                <span><strong>Direccion:</strong> <em>Belgrano 455</em></span>
                <br>
                <span><strong>Telefono:</strong> <em>011 4448 4545</em></span>
                <br>
                <span><strong>Email:</strong> <em>miempresa@lfj.com</em></span>
                <br>
                <span><strong>Region:</strong> <em>Argentina,_Tucuman,_Yerba-Buena</em></span>

            </div>
            </section>
            
    </body>
    {% endblock %}
</html>

project_prueba_tpo/templates/bloques/nosotros.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
<!--Cabecera-->
<head>
    <link rel="stylesheet" href="{% static './css/nosotros.css' %}">
</head>

<!-- Contenido principal -->

<section class="container content">
       
    <div>
        <img src="{% static '/assets/img/corpo.png' %}" class="corpo">
    </div>
    <div>

        <p>Nuestra empresa surge en los albores de la era digital, con el objetivo de proporcionar soluciones tecnológicas avanzadas y servicios de calidad en el campo de la conectividad. Desde nuestros humildes inicios, nos hemos enfocado en brindar servicios integrales que impulsen la transformación digital de nuestros clientes y les permitan aprovechar al máximo las oportunidades que ofrece internet.</p>

        <p>Nuestra visión es convertirnos en el referente indiscutible en el ámbito de la tecnología asociada a internet. Buscamos liderar el camino hacia una sociedad cada vez más conectada, donde las personas, las empresas y las comunidades puedan beneficiarse plenamente de las infinitas posibilidades que brinda la era digital. Aspiramos a ser reconocidos como la empresa que marca la pauta en innovación y excelencia en servicios tecnológicos.</p>

        <p>En consonancia con nuestra visión, nuestra misión es proporcionar soluciones tecnológicas de vanguardia que impulsen la productividad, la eficiencia y el crecimiento de nuestros clientes. Nos esforzamos por ofrecer servicios de internet confiables y veloces, garantizando una conectividad sin interrupciones. Buscamos superar las expectativas de nuestros clientes al brindarles un soporte técnico excepcional y soluciones a medida que satisfagan sus necesidades específicas.</p>

        <p>En resumen, somos una empresa dedicada a brindar servicios de tecnología asociados a internet, comprometidos con la excelencia, la innovación y la satisfacción del cliente. Estamos firmemente arraigados en nuestros valores de calidad, confiabilidad y servicio al cliente, y nos esforzamos por ser el socio tecnológico preferido para aquellos que desean aprovechar al máximo el potencial de la era digital.</p>
    </div>
</section>

<section>

    <h2>
      <strong>Imágenes</strong>
    </h2>
    <scroll-container id="scrollstyle">
      <img src="{% static '/assets/img/imlist-img-003.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-004.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-009.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-010.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-006.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-007.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-005.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-002.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-001.jpg' %}" alt="">
      <img src="{% static '/assets/img/imlist-img-008.jpg' %}" alt="">
    </scroll-clontainer>

  </section>
{% endblock %}

project_prueba_tpo/templates/bloques/servicios.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
<!--Cabecera-->
<head>
  <link rel="stylesheet" href="{% static './css/servicios.css' %}">
</head>

<!-- Youtube -->
<aside>
  <div>
    <h2 id="vid">Busca tu video favorito en YouTube</h2>
      <form onsubmit="buscarVideos(event)">
        <div>
         <input type="text" id="query" placeholder="Buscar videos en YouTube">
         <br>
         <button type="submit">Buscar</button>
        </div>
      </form>
  </div>
  <div id="videos"></div>
</aside>

<!-- Contenido principal -->

<main>

      <section id="internet">
        <h2>Internet</h2>
        <p>Ofrecemos servicios de internet de alta velocidad y confiabilidad. Nuestro enfoque está en proporcionar conectividad confiable para satisfacer las necesidades de nuestros clientes.</p>
      </section>

      <section id="telefonia">
        <h2>Telefonía</h2>
        <p>Contamos con servicios de telefonía de última generación que garantizan una comunicación clara y estable. Nuestro objetivo es brindar a nuestros clientes una experiencia excepcional en términos de calidad y fiabilidad de las llamadas.</p>
      </section>
    
      <section id="television">
        <h2>Televisión</h2>
        <p>Disfruta de una amplia variedad de contenido televisivo con nuestro servicio de IPTV. Te ofrecemos canales nacionales e internacionales, películas, series y eventos deportivos, todo transmitido a través de nuestra red segura y confiable.</p>
      </section>
    
      <section id="live_stream">
        <h2>Live Stream</h2>
        <p>Transmitimos eventos en vivo a través de nuestra plataforma de streaming. Ya sea un concierto, una conferencia o cualquier otro evento, puedes disfrutarlo desde la comodidad de tu hogar con una calidad de transmisión excepcional.</p>
      </section>
    
      <section id="cine">
        <h2>Servicios CINE</h2>
        <p>Sumérgete en el mundo del cine con nuestros servicios exclusivos. Te ofrecemos una amplia selección de películas de diferentes géneros y épocas para que puedas disfrutar del mejor entretenimiento en casa.</p>
      </section>
    
      <section id="web">
        <h2>Servicios WEB</h2>
        <p>Brindamos soluciones web personalizadas para empresas y particulares. Desde el diseño y desarrollo de sitios web hasta la implementación de aplicaciones web, nuestro equipo de expertos está listo para ayudarte a alcanzar tus objetivos en línea.</p>
      </section>    
  
    
  </main>

  

  <script src="{% static './assets/scripts/script.js' %}"></script>

{% endblock %}